name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate release notes
        uses: github-changelog-generator/github-changelog-generator-action@v2
        with:
          tag-name: ${{ github.ref_name }}
