name: Build, Release, and Publish

on:
  push:
    tags:
      - 'v*'  # 仅在 tag 推送时触发

jobs:
  # Step 1: 构建 Python 包
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build tools
        run: |
          pip install build
      - name: Build the package
        run: |
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/*  # 将构建的包上传为 Artifact

  # Step 2: 上传 GitHub Release 资产
  release:
    runs-on: ubuntu-latest
    needs: build  # 等待 build job 完成
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist  # 下载构建产物到 dist 目录
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Step 3: 发布到 PyPI
  publish:
    runs-on: ubuntu-latest
    needs: build  # 也依赖于 build job 完成
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install twine
        run: |
          pip install twine
      - name: Upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.TESTPYPI_TOKEN}}
        run: |
          python -m twine upload --repository testpypi dist/* --non-interactive
